name: "pulumi composite actions"
description: "A composite action wrapper around pulumi"
inputs:
  command:
    description: "The pulumi command to run"
    required: true
  stack:
    description: "The pulumi stack to use"
    required: true
  passphrase:
    description: "The passphrase to set for the project"
    required: false
    default: ""
  working_directory:
    description: "The directory to run all the commands in"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: pulumi
      env:
        PULUMI_STACK: ${{ inputs.stack }}
        PULUMI_CONFIG_PASSPHRASE: ${{ inputs.passphrase }}
      shell: bash
      id: main
      working-directory: ${{ inputs.working_directory }}
      run: ${{ github.action_path }}/main.sh "${{ inputs.command }}"
